### ISSUE TITLE
Energy Jolt Flashes When Neuron Stimulated

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/neuron#116] opened 2016-01-28 18:19 UTC
Related to https://github.com/phetsims/tasks/issues/485

Test device: Mac, Jordan

Operating System: OS X 10.9.5

Browser: Safari 9.0.1 (9537.86.2.7.2)

Problem description: The pulse that runs down the neuron flashes/drags when the neuron is stimulated 

Steps to reproduce: Stimulate neuron. Sometimes does not show unless sim is in full screen. 

Severity:

Screenshots: https://drive.google.com/file/d/0B_TAL-jnJOoKeWFjTkwzTFJka00/view?usp=sharing

Troubleshooting information (do not edit):
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html
Version: 1.0.0-rc.2 2016-01-23 00:14:48 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/537.86.2
Language: en-us
Window: 1358x598
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.28.36)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"d5e13134","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by jbphet** [comment] 2016-01-30 00:13
@elisemorgan - I watched the video a number of times and also tried to reproduce the issue on the same test device (Jordan).  I'm not seeing it.  Can you give me a bit more of a description of what you're concerned about?  Feel free to drop by my office if you like - I'll have Jordan with me for the next several work days.

**Comment by jbphet** [comment] 2016-02-05 19:46
@elisemorgan and I looked at this together, and basically the issue is that the frame rate on Safari bogs down a bit when the action potential is animating versus how it looks in other browsers.  It's not really flashing, it's just not perfectly smooth.  In my opinion, it looks acceptable, and is unlikely to distract or confuse users. I'm going to make the call and just close this, but @ariel-phet is welcome to reopen if he disagrees with my decision.

**Closed by jbphet** 2016-02-05 19:46 UTC

**Comment by ariel-phet** [comment] 2016-02-05 19:53
I am fine with that decision.
