### ISSUE TITLE
Chart line rendering on FF is not smooth

### ISSUE THREAD

**Issue by phet-steele** [phetsims/neuron#58] opened 2015-01-14 20:08 UTC
The red line on the potential chart looks very choppy/pixelated on Firefox 34.0:

![ff chart line](https://cloud.githubusercontent.com/assets/5863899/5746586/d1c7453e-9bed-11e4-8965-8c5d10fd2a53.png)

Here's Chrome's as a counter-example:

![ch chart line](https://cloud.githubusercontent.com/assets/5863899/5746601/ea5584da-9bed-11e4-8598-d1c97c65be56.png)

Viewed on 1.0.0-dev.7 with Win 8.1 64 bit

Troubleshooting information:
Name: Neuron
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.7/neuron_en.html
Version: 1.0.0-dev.7
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by orejolaphet** [comment] 2015-01-23 20:54
Also occurs in Win 8 IE 11

**Comment by jbphet** [comment] 2015-02-02 23:10
Looks fine for me running on Win 7, Firefox 35.0.1.  Screenshot:

![neuron-chart-looks-fine](https://cloud.githubusercontent.com/assets/3082831/6011101/99aadec4-aaf5-11e4-8f70-be5deafa34e3.png)

Could be that the issue is fixed in v35, or that it only occurs on some machines.  Here is the "Troubleshooting Information" that corresponds to this screenshot:

Troubleshooting information (do not edit):
Name: Neuron
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.8/neuron_en.html
Version: 1.0.0-dev.8
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1324x678
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment] 2015-02-02 23:19
Also looks fine for me in IE 11 on Win 7.  Screenshot:

![neuron-chart-looks-fine](https://cloud.githubusercontent.com/assets/3082831/6011259/ff1b1fa2-aaf6-11e4-8960-2eb63c2ba02e.png)

Troubleshooting information (do not edit):
Name: Neuron
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.8/neuron_en.html
Version: 1.0.0-dev.8
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; .NET4.0E; MALC; rv:11.0) like Gecko
Language: en-US
Window: 1489x747
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment] 2015-02-02 23:20
Perhaps this is machine dependent, based on the graphics capability of the given computer.  At any rate, it seems fairly low priority for now.

**Comment by jbphet** [comment] 2015-02-02 23:23
Assigning to myself, since I'll need to determine whether or not to address this.

**Comment by jbphet** [comment] 2015-09-23 19:16
I just tested the latest master version on my Win 7 machine, and the chart line looks fine on Firefox.  Assigning back to @phet-steele to gather more details about where and when this occurs.  If it is a small number of machines, we will likely close the issue without fixing it since it doesn't significantly affect usability.

**Comment by jbphet** [comment] 2015-09-23 19:18
Note to @phet-steele - it is probably best to test this using the PhET testing devices so that if you are able to duplicate it I can check it out easily.

**Comment by phet-steele** [comment] 2015-10-29 06:00
Here's what I have on FF 41.0.2, still not very smooth. I can check on a PhET device later:

![un-smooth](https://cloud.githubusercontent.com/assets/5863899/10811293/ff7eabd8-7dcf-11e5-8aa7-6c1ffd6b4fd1.PNG)

**Comment by ariel-phet** [comment] 2015-12-24 01:57
Looks completely acceptable to me now on Win 7 FF 43.0.2

![chart](https://cloud.githubusercontent.com/assets/4051174/11988062/f12dced0-a9a6-11e5-9abf-4b9d8b540efb.PNG)

Closing

**Closed by ariel-phet** 2015-12-24 01:57 UTC
Labels: low-priority
