### ISSUE TITLE
Game does not change state of pause/play buttons after pause and reset

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/neuron#90] opened 2015-10-13 16:42 UTC
If you pause and refresh the sim, the sim resumes in play mode but does not return pause/play section to  play settings.

To reproduce.
Open sim
hit pause
hit reset (Notice the the particles in the sim will begin to move again, but the pause/play section will remain in pause settings)

Troubleshooting information (do not edit):
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.13/neuron_en.html
Version: 1.0.0-dev.13 2015-10-09 19:02:48 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"47eaa1de","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"d93dfe7e","branch":"master"},"dot":{"sha":"09f891ac","branch":"master"},"griddle":{"sha":"bf88bc01","branch":"master"},"joist":{"sha":"3fbd99f9","branch":"master"},"kite":{"sha":"81ce58ca","branch":"master"},"neuron":{"sha":"1d73e47d","branch":"master"},"phet-core":{"sha":"f6348fba","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"8c246268","branch":"master"},"scenery-phet":{"sha":"4cf23e85","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"b66398a5","branch":"master"}}

**Comment by jbphet** [comment] 2015-10-14 22:40
This was fixed by commit https://github.com/phetsims/neuron/commit/1a96c36f103a75a3aec7ffc718b9b2a6e7aac502, and the issue is a duplicate of https://github.com/phetsims/neuron/issues/87, which was found shortly after publication of the dev version.  Closing.

**Closed by jbphet** 2015-10-14 22:40 UTC
