### ISSUE TITLE
Dragging ahead of the red line on the potential chart

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/neuron#143] opened 2020-03-03 17:33 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For ES6 Testing. 
When the sim is drawing the potential chart, you can drag the marker to look at past behavior. In the published sim you are unable to drag past the end of the red line. However, in master you can, and this causes some odd behavior. When you let go the red line draws in between the previous end and the new point. If you drag back to that area the sim movement is paused until the chart catches back up.
**Steps to reproduce**
1. Open the potential chart
2. Stimulate the neuron
3. Drag the blue marker forward as the peak is forming
4. Observe
5. Drag the marker back into the plateau area and observe

**Visuals**
![dragtothefuture](https://user-images.githubusercontent.com/41024075/75802708-64de5480-5d3a-11ea-873d-4e279ee0f1cc.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Neuron‬
URL: http://phettest.colorado.edu/neuron/build/phet/neuron_en_phet.html
Version: 1.2.0-dev.0 2020-03-03 16:44:47 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment] 2020-03-04 20:03
This appears to have been caused by https://github.com/phetsims/neuron/commit/5fcfcc575801f68a897039ff0aa1e1c4a895b19e, where some changes were made to the way the `DynamicSeries` type works.  I've fixed it.  

@samreid - tagging you since you made the change and might want to see what happened.

Closing.

**Closed by jbphet** 2020-03-04 20:03 UTC
Labels: type:bug
